// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEDC.EntityFramework.Demo.Data;

#nullable disable

namespace SEDC.EntityFramework.Demo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220706173914_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SEDC.EntityFramework.Demo.Data.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Skopje",
                            Name = "Seavus"
                        },
                        new
                        {
                            Id = 2,
                            City = "Bitola",
                            Name = "Seavus"
                        });
                });

            modelBuilder.Entity("SEDC.EntityFramework.Demo.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YearsOfExperiance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            FirstName = "Martin",
                            LastName = "Panovski",
                            YearsOfExperiance = 5
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            FirstName = "Jovana",
                            LastName = "Miskimovska",
                            YearsOfExperiance = 3
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            FirstName = "Stefan",
                            LastName = "Ivanovski",
                            YearsOfExperiance = 8
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            FirstName = "Dejan",
                            LastName = "Jovanov",
                            YearsOfExperiance = 4
                        });
                });

            modelBuilder.Entity("SEDC.EntityFramework.Demo.Data.Employee", b =>
                {
                    b.HasOne("SEDC.EntityFramework.Demo.Data.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SEDC.EntityFramework.Demo.Data.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
